site_name: Csound Plugins
theme: 
    name: readthedocs
    #highlightjs: true
    #hljs_languages:
    #    - csound
    include_homepage_in_sidebar: false
    prev_next_buttons_location: none
    titles_only: false
    sticky-navigation: false
    navigation_depth: 1
    
extra_css:
    - css/syntax-highlighting.css
    
markdown_extensions:
    - codehilite:
        guess_lang: false
        use_pygments: true
    - admonition

use_directory_urls: false

